### ISSUE TITLE
Improve UX of globe on website main page

### ISSUE THREAD

**Issue by skunk-ink** [SiaFoundation/web#405]
Prevent the globe from continuing to cycle through the available hosts when the user has one of the hosts selected. The globe should rotate to show the chosen host and stay there until the user unselects it or selects another host. Also, if the user could select to see the details of a host by clicking on the map, that would be nice as well. This is a very low priority, but it can cause frustration from a user experience standpoint.

**Comment by alexfreska** [comment]
The intended behaviour is pretty much what you are describing, with the one difference that instead of staying on a host until user deselects, it waits until the user stops interacting or hovering for a short period and resumes automatic rotations to a random host. Let me know if the video does not match your experience. 

https://github.com/SiaFoundation/web/assets/1412796/8a7ab41f-71d2-4460-ba52-f6c112c99e69

If by "see details of a host on the map" you mean a more detailed info card component like the one that pops up on the host bar, the underlying library limits to displaying only text, but we could have the info card appear in the bottom right or something.
